"""ticket summary added

Revision ID: 82cd20aca9ec
Revises: bf694d3f0217
Create Date: 2026-10-01 11:47:27.537752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82cd20aca9ec'
down_revision: Union[str, Sequence[str], None] = 'bf694d3f0217'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('summary', sa.String(), nullable=True))
    op.drop_column('tickets', 'language_checkpoint')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('language_checkpoint', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('tickets', 'summary')
    # ### end Alembic commands ###
