"""ticket auto increment id added, and other minor updates

Revision ID: bf694d3f0217
Revises: 1440e815d182
Create Date: 2026-10-01 11:37:39.940577

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf694d3f0217'
down_revision: Union[str, Sequence[str], None] = '1440e815d182'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('sessions_session_id_key'), 'sessions', type_='unique')
    op.drop_column('sessions', 'session_id')
    op.drop_constraint(op.f('tickets_ticket_id_key'), 'tickets', type_='unique')
    op.drop_column('tickets', 'ticket_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('ticket_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('tickets_ticket_id_key'), 'tickets', ['ticket_id'], postgresql_nulls_not_distinct=False)
    op.add_column('sessions', sa.Column('session_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('sessions_session_id_key'), 'sessions', ['session_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
